// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      return this.get('playerHand').on('hit', function() {
        var dealerhand, dealerscore, newhand, playerhand, playerscore;
        playerhand = this.get('playerHand');
        playerscore = playerhand.scores()[0];
        console.log(playerhand);
        dealerhand = this.get('dealerHand');
        dealerscore = dealerhand.scores()[0];
        if (playerscore > 21 || dealerscore > 21) {
          console.log("greater than 21");
          deck.initialize();
          newhand = deck.dealPlayer();
          this.set('playerHand', newhand);
          return console.log(playerhand);
        }
      }, this);
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
